// <auto-generated />
using System;
using JobPulse.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPulse.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JobPulseDbContext))]
    [Migration("20261002083944_AddJobListingDataQualityStatusIndex")]
    partial class AddJobListingDataQualityStatusIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPulse.Domain.Entities.ExperienceRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaximumYears")
                        .HasColumnType("int");

                    b.Property<int>("MinimumYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MinimumYears", "MaximumYears")
                        .IsUnique()
                        .HasFilter("[MaximumYears] IS NOT NULL");

                    b.ToTable("ExperienceRanges", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ExperienceRangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("JobListingSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastSeenAt");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OriginalPostedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("WorkMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CompanyName");

                    b.HasIndex("DataQualityStatus");

                    b.HasIndex("ExperienceRangeId");

                    b.HasIndex("JobListingSourceId");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("LocationId");

                    b.HasIndex("OriginalPostedDateUtc");

                    b.HasIndex("SourceIdentifier");

                    b.HasIndex("TechnologyId");

                    b.HasIndex("IsActive", "TechnologyId");

                    b.HasIndex("JobListingSourceId", "SourceIdentifier")
                        .IsUnique()
                        .HasFilter("[SourceIdentifier] IS NOT NULL");

                    b.ToTable("JobListings", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobListingSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("LastSuccessfulCollectionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobListingSources", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobSeeker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<Guid?>("ExperienceRangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("JobSearchStartDate")
                        .HasColumnType("date");

                    b.Property<string>("JobSearchStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<DateTime?>("LastConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OriginalRecordedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredWorkMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("ExperienceRangeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("LocationId");

                    b.HasIndex("OriginalRecordedDateUtc");

                    b.HasIndex("SourceIdentifier");

                    b.HasIndex("Source", "SourceIdentifier")
                        .IsUnique()
                        .HasFilter("[SourceIdentifier] IS NOT NULL");

                    b.ToTable("JobSeekers", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobSeekerSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerId");

                    b.HasIndex("LastUpdatedUtc");

                    b.HasIndex("TechnologyId");

                    b.HasIndex("JobSeekerId", "TechnologyId")
                        .IsUnique();

                    b.ToTable("JobSeekerSkills", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("India");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("City", "State", "Country")
                        .IsUnique()
                        .HasFilter("[State] IS NOT NULL");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.MarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveRegisteredJobSeekers")
                        .HasColumnType("int");

                    b.Property<int>("ActiveTrackedJobs")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewJobsLast30Days")
                        .HasColumnType("int");

                    b.Property<int>("NewJobsLast7Days")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SnapshotDate")
                        .IsUnique();

                    b.ToTable("MarketSnapshots", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Technologies", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.UserConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConsentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GrantedAtUtc");

                    b.HasIndex("JobSeekerId");

                    b.HasIndex("RevokedAtUtc");

                    b.HasIndex("JobSeekerId", "ConsentType", "IsGranted");

                    b.ToTable("UserConsents", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobListing", b =>
                {
                    b.HasOne("JobPulse.Domain.Entities.ExperienceRange", "ExperienceRange")
                        .WithMany("JobListings")
                        .HasForeignKey("ExperienceRangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPulse.Domain.Entities.JobListingSource", "JobListingSource")
                        .WithMany("JobListings")
                        .HasForeignKey("JobListingSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPulse.Domain.Entities.Location", "Location")
                        .WithMany("JobListings")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPulse.Domain.Entities.Technology", "Technology")
                        .WithMany("JobListings")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExperienceRange");

                    b.Navigation("JobListingSource");

                    b.Navigation("Location");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobSeeker", b =>
                {
                    b.HasOne("JobPulse.Domain.Entities.ExperienceRange", "ExperienceRange")
                        .WithMany("JobSeekers")
                        .HasForeignKey("ExperienceRangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JobPulse.Domain.Entities.Location", "Location")
                        .WithMany("JobSeekers")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExperienceRange");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobSeekerSkill", b =>
                {
                    b.HasOne("JobPulse.Domain.Entities.JobSeeker", "JobSeeker")
                        .WithMany("Skills")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPulse.Domain.Entities.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobSeeker");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.UserConsent", b =>
                {
                    b.HasOne("JobPulse.Domain.Entities.JobSeeker", "JobSeeker")
                        .WithMany("Consents")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.ExperienceRange", b =>
                {
                    b.Navigation("JobListings");

                    b.Navigation("JobSeekers");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobListingSource", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobSeeker", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.Location", b =>
                {
                    b.Navigation("JobListings");

                    b.Navigation("JobSeekers");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.Technology", b =>
                {
                    b.Navigation("JobListings");
                });
#pragma warning restore 612, 618
        }
    }
}
