// <auto-generated />
using System;
using JobPulse.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPulse.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JobPulseDbContext))]
    [Migration("20261002054929_InitialModel")]
    partial class InitialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPulse.Domain.Entities.ExperienceRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaximumYears")
                        .HasColumnType("int");

                    b.Property<int>("MinimumYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MinimumYears", "MaximumYears")
                        .IsUnique()
                        .HasFilter("[MaximumYears] IS NOT NULL");

                    b.ToTable("ExperienceRanges", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ExperienceRangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobListingSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OriginalPostedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("WorkMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("CompanyName");

                    b.HasIndex("ExperienceRangeId");

                    b.HasIndex("JobListingSourceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OriginalPostedDateUtc");

                    b.HasIndex("SourceIdentifier");

                    b.HasIndex("TechnologyId");

                    b.ToTable("JobListings", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobListingSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobListingSources", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("India");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("City", "State", "Country")
                        .IsUnique()
                        .HasFilter("[State] IS NOT NULL");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Technologies", (string)null);
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobListing", b =>
                {
                    b.HasOne("JobPulse.Domain.Entities.ExperienceRange", "ExperienceRange")
                        .WithMany("JobListings")
                        .HasForeignKey("ExperienceRangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPulse.Domain.Entities.JobListingSource", "JobListingSource")
                        .WithMany("JobListings")
                        .HasForeignKey("JobListingSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPulse.Domain.Entities.Location", "Location")
                        .WithMany("JobListings")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPulse.Domain.Entities.Technology", "Technology")
                        .WithMany("JobListings")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExperienceRange");

                    b.Navigation("JobListingSource");

                    b.Navigation("Location");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.ExperienceRange", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.JobListingSource", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.Location", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("JobPulse.Domain.Entities.Technology", b =>
                {
                    b.Navigation("JobListings");
                });
#pragma warning restore 612, 618
        }
    }
}
